version: "3.4"
services:
  cfwidget:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - database
      - memcache
    environment:
      DB_USER: widget
      DB_PASS: widget
      DB_HOST: database
      DB_DATABASE: widget
      GIN_MODE: release
      DEBUG: "false"
      CORE_KEY: "${CORE_KEY}"
      MEMCACHE_ENABLE: "true"
      MEMCACHE_HOST: memcache
      WEB_HOSTNAME: "${WEB_HOST}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cfwidget.rule=Host(`${WEB_HOST}`) || Host(`${API_HOST}`)"
      - "traefik.http.routers.cfwidget.entrypoints=websecure"
      - "traefik.http.routers.cfwidget.tls.certresolver=myresolver"
    volumes:
      - "logs:/logs"

  database:
    image: mariadb
    restart: always
    environment:
      MYSQL_USER: widget
      MYSQL_PASSWORD: widget
      MYSQL_DATABASE: widget
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
    command: ["mysqld", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
    ports:
    - "127.0.0.1:3306:3306"
    volumes:
      - "dbdata:/var/lib/mysql"

  memcache:
    image: memcached
    restart: always
    command: ["-m", "64m"]
  traefik:
    image: "traefik:v2.5"
    depends_on:
      - cfwidget
    command:
      #- "--log.level=debug"
      #- "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.email=${EMAIL_ACME}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      #- "--certificatesresolvers.myresolver.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
    ports:
      - "80:80"
      - "443:443"
      #- "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "traefik:/letsencrypt"

volumes:
  dbdata:
  traefik:
  logs: