version: "3.4"
services:
  cfwidget:
    image: ghcr.io/cfwidget/cfwidget
    restart: always
    depends_on:
      - database
    environment:
      DB_USER: widget
      DB_PASS_FILE: "/run/secrets/widget_db_pw"
      DB_HOST: database
      DB_DATABASE: widget
      DB_DEBUG: "false"
      GIN_MODE: release
      DEBUG: "false"
      CORE_KEY_FILE: "/run/secrets/core_key"
      WEB_HOSTNAME: "${WEB_HOST}"
      CACHE_TTL: "1h"
    secrets:
      - core_key
      - widget_db_pw
    networks:
      - default
      - ingress_default
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.${SERVICE_NAME}.rule=Host(`${WEB_HOST}`) || Host(`${API_HOST}`) || Host(`${ROOT_HOST}`)"
        - "traefik.http.routers.${SERVICE_NAME}.entrypoints=websecure"
        - "traefik.http.routers.${SERVICE_NAME}.tls.certresolver=myresolver"
        - "traefik.http.services.${SERVICE_NAME}.loadbalancer.server.port=8080"

  database:
    image: mariadb
    restart: always
    environment:
      MYSQL_USER: widget
      MYSQL_PASSWORD_FILE: "/run/secrets/widget_db_pw"
      MYSQL_DATABASE: widget
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
    command: ["mysqld", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
    volumes:
      - "dbdata:/var/lib/mysql"
    secrets:
      - widget_db_pw
    deploy:
      placement:
        constraints:
          - "node.role==manager"

secrets:
  core_key:
    external: true
  widget_db_pw:
    external: true

volumes:
  dbdata:

networks:
  ingress_default:
    external: true